---
# tasks file for ansible-homebrew

- name: Add homebrew line to ~/.zprofile
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: eval $(/opt/homebrew/bin/brew shellenv)
    create: true

- name: Ensure taps
  community.general.homebrew_tap:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
  loop: "{{ homebrew_taps }}"
  when: homebrew_taps|default([])|count > 0

- name: Ensure taps from GitHub
  community.general.homebrew_tap:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    url: "{{ item.url }}"
  loop: "{{ homebrew_taps_github }}"
  when: homebrew_taps_github|default([])|count > 0

- name: Ensure homebrew is up to date
  community.general.homebrew:
    update_homebrew: true

- name: Upgrade all homebrew packages
  community.general.homebrew:
    upgrade_all: true

- name: Upgrade all homebrew Casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Ensure packages
  community.general.homebrew:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  loop: "{{ homebrew_packages }}"
  when: homebrew_packages|default([])|count > 0

- name: Ensure packages removed
  community.general.homebrew:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('absent') }}"
  loop: "{{ homebrew_packages_removed }}"
  when: homebrew_packages_removed|default([])|count > 0

- name: Ensure apps
  community.general.homebrew_cask:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: true
  loop: "{{ homebrew_apps }}"
  when: homebrew_apps|default([])|count > 0

- name: Ensure apps removed
  community.general.homebrew_cask:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('absent') }}"
  loop: "{{ homebrew_apps_removed }}"
  when: homebrew_apps_removed|default([])|count > 0
